on: push
name: phpcs
jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP_CodeSniffer
        uses: chekalsky/phpcs-action@v1
